### ISSUE TITLE
Directory and leaf node

### ISSUE THREAD

**Issue by qguang** [christippett/ssm-parameter-store#7]
Thanks for this utility.

There is a small issue which I guess the use case itself is not really correct.

The current code doesn't handle the scenario below well. if one uses "directory" to store value. it will cause issue.
/test-path/rds/database
/test-path/rds/database/size
/test-path/rds/database/filePath

**Comment by christippett** [comment]
Hi @qguang, thanks for raising this. Can you provide some more detail about the issue you're having - it'd be handy to compare what you have in SSM and what you expect to have returned by the library. Thanks 😊

**Comment by qguang** [comment]
Hi @christippett 

I pasted code snippet which can be used to reproduce the "issue". Again, I don't think it is a genuine problem. However, it might require some improvement to handle the exception. 

`
from pprint import pprint
import boto3
from ssm_parameter_store import EC2ParameterStore

ssm_client = boto3.client("ssm")
# set up testing data in SSM
ssm_sample = dict(
    [
        
        ('/test-root-dir/database/movie_db','move_db'),
        ('/test-root-dir/database/movie_db/user1','app_user'),
        ('/test-root-dir/database/movie_db/password','we keep pwd in secret manager'),
    ]
)

for key, value in ssm_sample.items():
    new_parameter = ssm_client.put_parameter(
        Name = key,
        Value = value, 
        Description = 'Test SSM', Type = 'String', Overwrite=True,Tier='Standard',DataType='text'
    )

# initialize a store
store = EC2ParameterStore()
# get my parameters
parameters = store.get_parameters_with_hierarchy('/test-root-dir/database/', strip_path=True)

#!!!!! failure !!!!!#
>>> parameters = store.get_parameters_with_hierarchy('/test-root-dir/database/', strip_path=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../lib/python3.8/site-packages/ssm_parameter_store/stores.py", line 87, in get_parameters_with_hierarchy
    leafdict[key_segments[-1]] = value
TypeError: 'str' object does not support item assignment

# remove the testing parameters
ssm_keys = list(ssm_sample.keys())

response = ssm_client.delete_parameters(
            Names = ssm_keys
)
`
